export type MetricDef = {
  key: string;
  name: string;
  description: string;
  category: string;
  unit?: string;
  prefix?: string;
  icon: string;
  healthLow?: number;
  healthHigh?: number;
  healthNote?: string;
  businessTypes?: string[];
};

export const METRIC_LIBRARY: MetricDef[] = [
  // FINANCIAL
  {
    key: "monthly_revenue",
    name: "Monthly Revenue",
    description: "Total money earned in the current month before expenses.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "DollarSign",
    businessTypes: ["FREELANCER", "ECOMMERCE", "SERVICE_BUSINESS", "SAAS", "CREATOR", "SIDE_HUSTLE"],
  },
  {
    key: "annual_revenue",
    name: "Annual Revenue",
    description: "Total revenue earned in the current year.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "TrendingUp",
    businessTypes: ["FREELANCER", "ECOMMERCE", "SERVICE_BUSINESS", "SAAS"],
  },
  {
    key: "net_profit",
    name: "Net Profit",
    description: "Revenue minus all expenses. The money you actually keep.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "Wallet",
    businessTypes: ["FREELANCER", "ECOMMERCE", "SERVICE_BUSINESS", "SAAS"],
  },
  {
    key: "profit_margin",
    name: "Profit Margin",
    description: "Net profit as a percentage of revenue. Healthy range: 20–40% for service businesses.",
    category: "FINANCIAL",
    unit: "%",
    icon: "Percent",
    healthLow: 20,
    healthHigh: 40,
    healthNote: "Healthy profit margin for a service business: 20–40%. Below 10% is a warning sign.",
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS", "SAAS"],
  },
  {
    key: "monthly_expenses",
    name: "Monthly Expenses",
    description: "Total money spent running your business this month.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "Receipt",
    businessTypes: ["FREELANCER", "ECOMMERCE", "SERVICE_BUSINESS", "SAAS", "SIDE_HUSTLE"],
  },
  {
    key: "burn_rate",
    name: "Burn Rate",
    description: "How much cash you're spending per month. Critical for startups and pre-revenue businesses.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "Flame",
    businessTypes: ["SAAS"],
  },
  {
    key: "runway_months",
    name: "Runway (Months)",
    description: "How many months you can operate at current burn rate. Keep above 12.",
    category: "FINANCIAL",
    unit: "mo",
    icon: "Timer",
    healthLow: 12,
    healthNote: "Keep at least 12 months of runway. Below 6 months is a crisis.",
    businessTypes: ["SAAS"],
  },
  {
    key: "cash_balance",
    name: "Cash Balance",
    description: "Total money currently in your business accounts.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "Banknote",
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS", "SAAS", "SIDE_HUSTLE"],
  },
  {
    key: "outstanding_invoices",
    name: "Outstanding Invoices",
    description: "Money owed to you that hasn't been paid yet.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "FileText",
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS"],
  },
  // SALES
  {
    key: "mrr",
    name: "Monthly Recurring Revenue",
    description: "Predictable monthly revenue from subscriptions or retainers. The lifeblood of subscription businesses.",
    category: "SALES",
    prefix: "$",
    icon: "RefreshCw",
    businessTypes: ["SAAS"],
  },
  {
    key: "arr",
    name: "Annual Recurring Revenue",
    description: "MRR × 12. The standard measure of SaaS business scale.",
    category: "SALES",
    prefix: "$",
    icon: "BarChart3",
    businessTypes: ["SAAS"],
  },
  {
    key: "new_customers",
    name: "New Customers",
    description: "Number of new paying customers acquired this month.",
    category: "SALES",
    unit: "customers",
    icon: "UserPlus",
    businessTypes: ["SAAS", "ECOMMERCE", "SERVICE_BUSINESS"],
  },
  {
    key: "active_clients",
    name: "Active Clients",
    description: "Number of clients you're currently working with.",
    category: "SALES",
    unit: "clients",
    icon: "Users",
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS"],
  },
  {
    key: "close_rate",
    name: "Close Rate",
    description: "Percentage of leads that convert to paying clients. Healthy: 20–40%.",
    category: "SALES",
    unit: "%",
    icon: "CheckCircle",
    healthLow: 20,
    healthHigh: 40,
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS", "SAAS"],
  },
  {
    key: "average_deal_size",
    name: "Average Deal Size",
    description: "Average revenue per new client or sale.",
    category: "SALES",
    prefix: "$",
    icon: "DollarSign",
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS", "SAAS"],
  },
  {
    key: "churn_rate",
    name: "Churn Rate",
    description: "Percentage of customers who cancelled this month. Keep below 5% monthly.",
    category: "SALES",
    unit: "%",
    icon: "UserMinus",
    healthHigh: 5,
    healthNote: "Monthly churn above 5% means you're losing customers faster than you can acquire them.",
    businessTypes: ["SAAS"],
  },
  {
    key: "customer_ltv",
    name: "Customer LTV",
    description: "Average total revenue from a single customer over their lifetime.",
    category: "SALES",
    prefix: "$",
    icon: "Heart",
    businessTypes: ["SAAS", "ECOMMERCE", "SERVICE_BUSINESS"],
  },
  {
    key: "cac",
    name: "Customer Acquisition Cost",
    description: "How much you spend to acquire each new customer. Should be < 1/3 of LTV.",
    category: "SALES",
    prefix: "$",
    icon: "Target",
    businessTypes: ["SAAS", "ECOMMERCE"],
  },
  // ECOMMERCE
  {
    key: "total_orders",
    name: "Total Orders",
    description: "Number of orders placed this month.",
    category: "SALES",
    unit: "orders",
    icon: "ShoppingBag",
    businessTypes: ["ECOMMERCE"],
  },
  {
    key: "average_order_value",
    name: "Average Order Value",
    description: "Average revenue per order. Increase it with upsells and bundles.",
    category: "SALES",
    prefix: "$",
    icon: "ShoppingCart",
    businessTypes: ["ECOMMERCE"],
  },
  {
    key: "refund_rate",
    name: "Refund Rate",
    description: "Percentage of orders refunded. Keep below 3% for ecommerce.",
    category: "SALES",
    unit: "%",
    icon: "RotateCcw",
    healthHigh: 3,
    businessTypes: ["ECOMMERCE"],
  },
  {
    key: "conversion_rate",
    name: "Conversion Rate",
    description: "Percentage of visitors who make a purchase. Ecommerce average: 2–4%.",
    category: "MARKETING",
    unit: "%",
    icon: "Zap",
    healthLow: 2,
    healthHigh: 4,
    businessTypes: ["ECOMMERCE", "SAAS"],
  },
  // MARKETING
  {
    key: "website_visitors",
    name: "Website Visitors",
    description: "Unique visitors to your website this month.",
    category: "MARKETING",
    unit: "visitors",
    icon: "Globe",
    businessTypes: ["ECOMMERCE", "SAAS", "CREATOR"],
  },
  {
    key: "email_subscribers",
    name: "Email Subscribers",
    description: "Total email list size. Your most valuable marketing asset.",
    category: "MARKETING",
    unit: "subscribers",
    icon: "Mail",
    businessTypes: ["CREATOR", "SAAS", "ECOMMERCE"],
  },
  {
    key: "social_followers",
    name: "Social Followers",
    description: "Combined follower count across your primary social platforms.",
    category: "MARKETING",
    unit: "followers",
    icon: "Share2",
    businessTypes: ["CREATOR", "SIDE_HUSTLE"],
  },
  // TIME & PRODUCTIVITY
  {
    key: "billable_hours",
    name: "Billable Hours",
    description: "Hours spent on client or revenue-generating work this month.",
    category: "TIME",
    unit: "hours",
    icon: "Clock",
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS"],
  },
  {
    key: "effective_hourly_rate",
    name: "Effective Hourly Rate",
    description: "Revenue divided by hours worked. Are you charging enough?",
    category: "TIME",
    prefix: "$",
    unit: "/hr",
    icon: "Clock",
    businessTypes: ["FREELANCER", "SERVICE_BUSINESS"],
  },
  {
    key: "hours_worked",
    name: "Hours Worked",
    description: "Total hours worked this month across all projects.",
    category: "TIME",
    unit: "hours",
    icon: "Timer",
    businessTypes: ["FREELANCER", "SIDE_HUSTLE", "SERVICE_BUSINESS"],
  },
  // CREATOR
  {
    key: "content_pieces",
    name: "Content Published",
    description: "Number of pieces of content published this month.",
    category: "GROWTH",
    unit: "pieces",
    icon: "FileText",
    businessTypes: ["CREATOR"],
  },
  {
    key: "views",
    name: "Views / Plays",
    description: "Total views or plays across your content this month.",
    category: "GROWTH",
    unit: "views",
    icon: "Eye",
    businessTypes: ["CREATOR"],
  },
  // GROWTH
  {
    key: "revenue_growth",
    name: "Revenue Growth Rate",
    description: "Month-over-month revenue growth as a percentage.",
    category: "GROWTH",
    unit: "%",
    icon: "TrendingUp",
    businessTypes: ["FREELANCER", "ECOMMERCE", "SERVICE_BUSINESS", "SAAS"],
  },
  {
    key: "customer_growth",
    name: "Customer Growth Rate",
    description: "Month-over-month growth in customer count.",
    category: "GROWTH",
    unit: "%",
    icon: "Users",
    businessTypes: ["SAAS", "ECOMMERCE"],
  },
  // SIDE HUSTLE
  {
    key: "income_source_1",
    name: "Income Source 1",
    description: "Revenue from your primary income stream. Rename to match your source.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "DollarSign",
    businessTypes: ["SIDE_HUSTLE"],
  },
  {
    key: "income_source_2",
    name: "Income Source 2",
    description: "Revenue from your secondary income stream.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "DollarSign",
    businessTypes: ["SIDE_HUSTLE"],
  },
  {
    key: "total_income",
    name: "Total Income",
    description: "Combined revenue from all income streams this month.",
    category: "FINANCIAL",
    prefix: "$",
    icon: "Wallet",
    businessTypes: ["SIDE_HUSTLE", "FREELANCER"],
  },
  {
    key: "tax_estimate",
    name: "Tax Estimate",
    description: "Estimated taxes owed based on income (25–30% of profit is a safe estimate).",
    category: "FINANCIAL",
    prefix: "$",
    icon: "Receipt",
    businessTypes: ["SIDE_HUSTLE", "FREELANCER"],
  },
  // CUSTOMER
  {
    key: "nps_score",
    name: "Net Promoter Score",
    description: "How likely customers are to recommend you. Good: 50+, Excellent: 70+.",
    category: "CUSTOMER",
    icon: "Star",
    healthLow: 50,
    healthHigh: 100,
    businessTypes: ["SAAS", "SERVICE_BUSINESS"],
  },
  {
    key: "support_tickets",
    name: "Support Tickets",
    description: "Number of support requests received this month.",
    category: "CUSTOMER",
    unit: "tickets",
    icon: "MessageCircle",
    businessTypes: ["SAAS", "ECOMMERCE"],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  FINANCIAL: "Financial",
  SALES: "Sales & Revenue",
  MARKETING: "Marketing",
  OPERATIONS: "Operations",
  TIME: "Time & Productivity",
  GROWTH: "Growth",
  CUSTOMER: "Customer",
  CUSTOM: "Custom",
};

export function getMetricsByBusinessType(type: string): MetricDef[] {
  return METRIC_LIBRARY.filter(
    (m) => !m.businessTypes || m.businessTypes.includes(type)
  );
}

export function getMetricByKey(key: string): MetricDef | undefined {
  return METRIC_LIBRARY.find((m) => m.key === key);
}
